"""Day-1 census report, rendered from the ledger.

Single renderer: stdout and census/report.md come from the same queries, so the
two can never disagree. Every number below is a query over ledger/colim.sqlite;
nothing is transcribed by hand.

  python3 census/report.py            # print
  python3 census/report.py --write    # also refresh census/report.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ledger.db import connect, get_meta  # noqa: E402

OUT_PATH = Path(__file__).resolve().parent / "report.md"


def render() -> str:
    conn = connect()
    q = lambda sql, *a: conn.execute(sql, a).fetchall()  # noqa: E731
    one = lambda sql, *a: conn.execute(sql, a).fetchone()[0]  # noqa: E731
    L: list[str] = []
    w = L.append

    eval_tc = get_meta(conn, "eval_toolchain")
    coverage = float(get_meta(conn, "eval_toolchain_coverage"))
    indexed = one("SELECT COUNT(*) FROM packages")
    k = one("SELECT COUNT(*) FROM packages WHERE in_k=1")
    archived = one("SELECT COUNT(*) FROM packages WHERE final_status='ARCHIVED'")
    vanished = one("SELECT COUNT(*) FROM packages WHERE final_status='VANISHED'")
    m = one("SELECT COUNT(*) FROM packages WHERE in_k=1 AND final_status='RED_REGRESSION'")

    w("# Colim Day-1 Census")
    w("")
    w("Generated by `census/report.py` from `ledger/colim.sqlite`. Do not edit by hand.")
    w("")
    w("| provenance | value |")
    w("|---|---|")
    w(f"| Reservoir index snapshot | `{get_meta(conn, 'index_commit')}` |")
    w(f"| snapshot committed | {get_meta(conn, 'index_committed_at')} |")
    w(f"| GitHub metadata fetched | {get_meta(conn, 'github_meta_fetched_at')} |")
    w(f"| evaluation toolchain | `{eval_tc}` |")
    w(f"| build coverage on that toolchain | {coverage:.1%} of indexed packages |")
    w("")

    w("## Headline")
    w("")
    w(f"**K = {k}**  ·  **M = {m}**  ·  **M/K = {m / k:.1%}**")
    w("")
    w(
        f"{m} of {k} in-scope packages in Lean's official registry are red regressions "
        f"on `{eval_tc}` — they build on some earlier toolchain but fail when forced "
        "onto the evaluation toolchain."
    )
    w("")

    w("## Scope")
    w("")
    w("| | n | meaning |")
    w("|---|---|---|")
    w(f"| indexed packages | {indexed} | every package in the Reservoir index |")
    w(f"| `ARCHIVED` | {archived} | upstream archived the repo — excluded from K and M |")
    w(f"| `VANISHED` | {vanished} | source no longer resolves — excluded from K and M |")
    w(f"| **K** | **{k}** | indexed, in scope |")
    w("")

    w(f"## Classification on `{eval_tc}`")
    w("")
    w(f"Denominator K = {k}.")
    w("")
    w("| status | n | % of K |")
    w("|---|---:|---:|")
    for r in q(
        "SELECT final_status s, COUNT(*) n FROM packages WHERE in_k=1 "
        "GROUP BY s ORDER BY n DESC"
    ):
        w(f"| `{r['s']}` | {r['n']} | {r['n'] / k:.1%} |")
    w("")
    never = one("SELECT COUNT(*) FROM packages WHERE in_k=1 AND final_status='NEVER_GREEN'")
    w(
        f"`NEVER_GREEN` ({never}) is excluded from the headline by definition: those packages "
        "never built green on any toolchain, so they cannot have regressed."
    )
    w("")

    forced = one(
        "SELECT COUNT(*) FROM packages WHERE in_k=1 AND final_status='FORCED_DOWNGRADE'"
    )
    if forced:
        w("### `FORCED_DOWNGRADE` — pinned ahead of the evaluation toolchain")
        w("")
        w(
            f"Reservoir forces the toolchain, so these {forced} packages fail because their "
            "source is **too new** for `v4.32.1`, not because upstream broke them. A "
            "forced-backwards failure is the opposite of a regression, so they are not in M."
        )
        w("")
        w("| stars | package | pins |")
        w("|---:|---|---|")
        for r in q(
            "SELECT pkg_key, stars, old_toolchain FROM packages WHERE in_k=1 "
            "AND final_status='FORCED_DOWNGRADE' ORDER BY stars DESC"
        ):
            w(f"| {r['stars']} | `{r['pkg_key']}` | `{r['old_toolchain']}` |")
        w("")

    w("## Mathlib-downstream subset (campaign target)")
    w("")
    km = one("SELECT COUNT(*) FROM packages WHERE in_k=1 AND mathlib_downstream=1")
    km_red = one(
        "SELECT COUNT(*) FROM packages WHERE in_k=1 AND mathlib_downstream=1 "
        "AND final_status='RED_REGRESSION'"
    )
    campaign = one(
        "SELECT COUNT(*) FROM packages WHERE in_k=1 AND mathlib_downstream=1 "
        "AND final_status='RED_REGRESSION' AND release_train=0"
    )
    w("Reported against its own denominator K_m, never swapped for K.")
    w("")
    w("| | n |")
    w("|---|---:|")
    w(f"| K_m (mathlib-dependent, in K) | {km} |")
    w(f"| red regressions within K_m | {km_red} ({km_red / km:.1%} of K_m) |")
    w(f"| **Day-6 campaign set** (K_m red, minus release train) | **{campaign}** |")
    w("")

    w("## Recency slice")
    w("")
    w(
        "Staleness never excludes a package — abandoned-but-once-green is the market. "
        "This slice is shown because a skeptic will ask for it."
    )
    w("")
    w("| active within | K | M | M/K |")
    w("|---|---:|---:|---:|")
    for label, cutoff in (("12 months", "2025-07-27"), ("24 months", "2024-07-27")):
        tot = one("SELECT COUNT(*) FROM packages WHERE in_k=1 AND last_commit>=?", cutoff)
        red = one(
            "SELECT COUNT(*) FROM packages WHERE in_k=1 AND last_commit>=? "
            "AND final_status='RED_REGRESSION'",
            cutoff,
        )
        w(f"| {label} | {tot} | {red} | {red / tot:.1%} |")
    w("")

    w("## Failure origin")
    w("")
    rows = q(
        "SELECT COALESCE(failure_origin,'unknown') o, COUNT(*) n FROM packages "
        "WHERE in_k=1 AND final_status='RED_REGRESSION' GROUP BY o ORDER BY n DESC"
    )
    resolved = sum(r["n"] for r in rows if r["o"] != "unknown")
    if resolved:
        w("Classified from Reservoir's public build logs. Dependency rot is the product")
        w("thesis, so the split is counted and disclosed rather than hidden.")
        w("")
        w("| origin | n | % of resolved |")
        w("|---|---:|---:|")
        for r in rows:
            pct = f"{r['n'] / resolved:.1%}" if r["o"] != "unknown" else "—"
            w(f"| `{r['o']}` | {r['n']} | {pct} |")
        w("")
        w(f"Resolved for {resolved} of {m} reds. The split is reported against the")
        w("resolved subset only and is never extrapolated to the remainder.")
    else:
        w(f"Not yet resolved — `unknown` for all {m} reds pending Day-2 log analysis.")
        w("The self/dependency split must not be claimed until then.")
    w("")

    w("## Day-2 spot-check candidates")
    w("")
    w("Top red regressions by stars. `M` marks mathlib-downstream.")
    w("")
    w("| stars | | package | pins | last commit |")
    w("|---:|---|---|---|---|")
    for r in q(
        "SELECT pkg_key, stars, old_toolchain, last_commit, mathlib_downstream "
        "FROM packages WHERE in_k=1 AND final_status='RED_REGRESSION' "
        "AND release_train=0 ORDER BY stars DESC LIMIT 25"
    ):
        tc = (r["old_toolchain"] or "?").replace("leanprover/lean4:", "")
        mark = "M" if r["mathlib_downstream"] else ""
        w(
            f"| {r['stars']} | {mark} | `{r['pkg_key']}` | `{tc}` | "
            f"{(r['last_commit'] or '?')[:10]} |"
        )
    w("")

    w("## Caveats that travel with these numbers")
    w("")
    w(
        "1. **Reservoir forces the toolchain.** Packages are built against "
        f"`{eval_tc}` regardless of the toolchain they pin. \"Red\" therefore means "
        "*fails when forced onto v4.32.1*, not *the maintainer's own pinned build is "
        "broken*. That is the intended regression question, stated in those words."
    )
    w(
        f"2. **{archived} archived and {vanished} vanished packages are outside K and M.** "
        "Vanished packages can never enter N — there is no repo to fork."
    )
    w(
        "3. **Classification uses Reservoir's recorded outcomes, not local rebuilds.** "
        "Day 2 reproduces a sample locally to check Reservoir against reality."
    )
    w(
        "4. **Coverage is not 100%.** The evaluation toolchain has a recorded outcome for "
        f"{coverage:.1%} of indexed packages; the remainder is `UNKNOWN`, never guessed."
    )
    w("")
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="refresh census/report.md")
    args = ap.parse_args()

    text = render()
    print(text)
    if args.write:
        OUT_PATH.write_text(text + "\n")
        print(f"\n[wrote {OUT_PATH}]", file=sys.stderr)


if __name__ == "__main__":
    main()
